routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/about', 'AboutController@index')->name('about.index');
Route::get('/admin/about', 'AboutController@edit')->name('about.edit');
Route::put('/admin/about', 'AboutController@update')->name('about.update');

Route::get('/me', 'User\UserController@show')->name('me');
Route::get('/me/orders', 'User\UserOrderController@index')->name('users.order');

Route::get('/admin', 'Admin\AdminController@index')->name('admin.index')->middleware('auth', 'admin');
Route::get('/admin', 'Admin\AdminController@index')->name('admin.index')->middleware('auth', 'admin');

Route::get('/cart', 'CartController@index')->name('cart.index');
Route::get('/cart/{item}/remove', 'CartController@destroy')->name('cart.destroy');
Route::put('/cart/{item}', 'CartController@update')->name('cart.update');

Route::get('/search', 'SearchController@index')->name('search.index');
Route::post('/search', 'SearchController@index')->name('search.index');

Route::get('categories/{category}/products', 'CategoryProductController@show')->name('categories.products');

Route::resource('products', 'ProductController');
Route::get('products/{product}/add', 'ProductShoppingController@show');
Route::post('products/{product}/add', 'ProductShoppingController@store')->name('products.add');

Route::resource('reviews', 'Product\ProductReviewController');
Route::resource('orders', 'Admin\OrderController');

Route::get('/activate/{token}', 'ActivationController@show')->name('active');

Route::resource('categories', 'Admin\CategoryController', [
    'middleware' => ['auth', 'admin']
]);

Route::post('/cart/pay', 'CheckoutController@store')->name('checkout');
Route::get('/thank-you', 'HomeController@thanks')->name('thank-you');
Route::post('stripe/webhook', '\Laravel\Cashier\Http\Controllers\WebhookController@handleWebhook');

app/Models/Product.php
<?php

namespace App\Models;

use App\Models\Extensions\Uploadable;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use Sluggable, SoftDeletes, Uploadable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'category_id', 'name', 'slug', 'description',
        'price', 'stock',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'image_path'
    ];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function reviews()
    {
        return $this->hasMany(Review::class);
    }
}

app/Http/Controllers/Product/ProductReviewController.php
<?php

namespace App\Http\Controllers\Product;

use App\Models\Review;
use App\Http\Controllers\Controller;
use App\Http\Requests\Product\Review\StoreRequest;
use App\Http\Requests\Product\Review\UpdateRequest;

class ProductReviewController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Product\Review\StoreRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $review = $request->persist();

        return redirect()->route('products.show', $review->product);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Review  $review
     * @return \Illuminate\Http\Response
     */
    public function show(Review $review)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Review  $review
     * @return \Illuminate\Http\Response
     */
    public function edit(Review $review)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Product\Review\UpdateRequest  $request
     * @param  \App\Models\Review  $review
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, Review $review)
    {
        $request->persist();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Review  $review
     * @return \Illuminate\Http\Response
     */
    public function destroy(Review $review)
    {
        //
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\Category;
use App\Http\Requests\Product\StoreRequest;
use App\Http\Requests\Product\UpdateRequest;

class ProductController extends Controller
{
    /**
     * ProductController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth', [
            'except' => ['show']
        ]);

        $this->middleware('admin', [
            'except' => ['show']
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::with('category')->paginate(15);

        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::with('subCategories')->where('category_id', 0)->get();

        return view('product.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $product = $request->persist();

        return redirect()->route('products.show', $product);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $categories = Category::with('subCategories')->where('category_id', 0)->get();

        return view('product.edit', compact('product', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateRequest  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, Product $product)
    {
        $request->persist();

        return redirect()->route('products.show', $product);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();

        return redirect()->route('products.index');
    }
}

resources/views/product/create.blade.php
@extends('layouts.admin')

@section('breadcrumbs')
    {!! Laracrumbs::render() !!}
@endsection

@section('admin-content')
    <div class="col-md-6">
        <form action="{{ route('products.store') }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name">Product Name</label>
                <input type="text" class="form-control" id="name" name="name"
                       value="{{ old('name') }}">

                @if ($errors->has('name'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('name') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('category_id') ? ' has-error' : '' }}">
                <label for="category_id">Category of</label>
                <select class="selectable-group form-control" id="category_id" name="category_id">
                    <option value="" disabled selected>Select a category</option>
                    @foreach($categories as $category)
                        <option value="{{ $category->id }}" {{ selected($category) }}
                        class="category">{{ $category->name }}</option>

                        @foreach($category->subCategories as $subCategory)
                            <option value="{{ $subCategory->id }}" {{ selected($category) }}
                                    class="item">{{ $subCategory->name }}</option>
                        @endforeach
                    @endforeach
                </select>

                @if ($errors->has('category_id'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('category_id') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                <label for="description">Description</label>
                <textarea class="form-control product-description" id="description"
                          name="description">{{ old('description') }}</textarea>

                @if ($errors->has('description'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('description') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('cover') ? ' has-error' : '' }}">
                <label for="cover">Product image cover</label>
                <input type="file" id="cover" name="cover">
                <p class="help-block">This image is used as cover.</p>

                @if ($errors->has('cover'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('cover') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
                <label for="price">Price (in euros)</label>
                <div class="input-group">
                    <div class="input-group-addon">&euro;</div>
                    <input type="number" class="form-control" id="price" name="price" min="0" step="any"
                           value="{{ old('price', 0) }}">
                </div>

                @if ($errors->has('price'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('price') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('stock') ? ' has-error' : '' }}">
                <label for="stock">Stock</label>
                <input type="number" class="form-control" id="stock" name="stock" min="0"
                       value="{{ old('stock', 0) }}">
                <p class="help-block">The amount of products currently in stock.</p>

                @if ($errors->has('stock'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('stock') }}</strong>
                    </p>
                @endif
            </div>

            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.admin')

@section('breadcrumbs')
    {!! Laracrumbs::render($product) !!}
@endsection

@section('admin-content')
    <div class="col-md-6">
        <form action="{{ route('products.update', $product) }}" method="post" enctype="multipart/form-data">
            {{ method_field('PUT') }}
            {{ csrf_field() }}

            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name">Product Name</label>
                <input type="text" class="form-control" id="name" name="name"
                       value="{{ old('name', $product->name) }}">

                @if ($errors->has('name'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('name') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('category_id') ? ' has-error' : '' }}">
                <label for="category_id">Category of</label>
                <select class="selectable-group form-control" id="category_id" name="category_id">
                    <option value="" disabled selected>Select a category</option>
                    @foreach($categories as $category)
                        <option value="{{ $category->id }}" {{ selected($category, $product->category_id) }}
                            class="category">{{ $category->name }}</option>

                        @foreach($category->subCategories as $subCategory)
                            <option value="{{ $subCategory->id }}" {{ selected($subCategory, $product->category_id) }}
                                class="item">{{ $subCategory->name }}</option>
                        @endforeach
                    @endforeach
                </select>

                @if ($errors->has('category_id'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('category_id') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                <label for="description">Description</label>
                <textarea class="form-control product-description" id="description"
                          name="description">{{ old('description', $product->description) }}</textarea>

                @if ($errors->has('description'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('description') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('cover') ? ' has-error' : '' }}">
                <label for="cover">Product image cover</label>
                <input type="file" id="cover" name="cover">
                <p class="help-block">This image is used as cover.</p>

                @if ($errors->has('cover'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('cover') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
                <label for="price">Price (in euros)</label>
                <div class="input-group">
                    <div class="input-group-addon">&euro;</div>
                    <input type="number" class="form-control" id="price" name="price" min="0" step="any"
                           value="{{ old('price', $product->price) }}">
                </div>

                @if ($errors->has('price'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('price') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('stock') ? ' has-error' : '' }}">
                <label for="stock">Stock</label>
                <input type="number" class="form-control" id="stock" name="stock" min="0"
                       value="{{ old('stock', $product->stock) }}">
                <p class="help-block">The amount of products currently in stock.</p>

                @if ($errors->has('stock'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('stock') }}</strong>
                    </p>
                @endif
            </div>

            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.admin')

@section('breadcrumbs')
    {!! Laracrumbs::render() !!}
@endsection

@section('admin-content')
    <div class="col-md-9">
        <p>
            <a href="{{ route('products.create') }}" class="btn btn-default">Create product</a>
        </p>
        <table class="table table-striped">
            <tr>
                <th>
                    #
                </th>
                <th>
                    Name
                </th>
                <th>
                    Category
                </th>
            </tr>
            @foreach($products as $product)
                <tr>
                    <td>
                        {{ $product->id }}
                    </td>
                    <td>
                        <a href="{{ route('products.show', $product) }}">
                            {{ $product->name }}
                        </a>
                    </td>
                    <td>
                        <a href="{{ route('categories.show', $product->category) }}">
                            {{ $product->category->name }}
                        </a>
                    </td>
                </tr>
            @endforeach
        </table>
        {{ $products->links() }}
    </div>
@endsection

resources/views/product/show.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    {!! Laracrumbs::render($product) !!}
@endsection

@section('content')
    <div class="col-md-3">
        <img src="{{ $product->getImagePathAttribute() }}" alt="{{ $product->name }}" width="100%">
    </div>
    <div class="col-md-9">
        <p>
            {{ $product->name }}
        </p>
        <p>
            {{ $product->description }}
        </p>
        <p>
            Price: &euro; {{ $product->price }}
        </p>
        <p>
            In stock: {{ $product->stock }}
        </p>

        <a href="{{ route('products.add', $product->slug) }}" class="btn btn-primary btn-lg add-to-cart"
           data-turbolinks="false">
            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
        </a>

        @if (is_admin())
            <a href="{{ route('products.edit', $product) }}" class="btn btn-default">Edit</a>

            <a href="{{ route('products.destroy', $product) }}" class="btn btn-warning"
               onclick="event.preventDefault(); document.getElementById('delete-form').submit();">
                Delete
            </a>

            <form id="delete-form" action="{{ route('products.destroy', $product) }}" method="POST" style="display: none;">
                {{ csrf_field() }}
                {{ method_field('DELETE') }}
            </form>
        @endif
    </div>
@endsection