routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/about', 'AboutController@index')->name('about.index');
Route::get('/admin/about', 'AboutController@edit')->name('about.edit');
Route::put('/admin/about', 'AboutController@update')->name('about.update');

Route::get('/me', 'User\UserController@show')->name('me');
Route::get('/me/orders', 'User\UserOrderController@index')->name('users.order');

Route::get('/admin', 'Admin\AdminController@index')->name('admin.index')->middleware('auth', 'admin');
Route::get('/admin', 'Admin\AdminController@index')->name('admin.index')->middleware('auth', 'admin');

Route::get('/cart', 'CartController@index')->name('cart.index');
Route::get('/cart/{item}/remove', 'CartController@destroy')->name('cart.destroy');
Route::put('/cart/{item}', 'CartController@update')->name('cart.update');

Route::get('/search', 'SearchController@index')->name('search.index');
Route::post('/search', 'SearchController@index')->name('search.index');

Route::get('categories/{category}/products', 'CategoryProductController@show')->name('categories.products');

Route::resource('products', 'ProductController');
Route::get('products/{product}/add', 'ProductShoppingController@show');
Route::post('products/{product}/add', 'ProductShoppingController@store')->name('products.add');

Route::resource('reviews', 'Product\ProductReviewController');
Route::resource('orders', 'Admin\OrderController');

Route::get('/activate/{token}', 'ActivationController@show')->name('active');

Route::resource('categories', 'Admin\CategoryController', [
    'middleware' => ['auth', 'admin']
]);

Route::post('/cart/pay', 'CheckoutController@store')->name('checkout');
Route::get('/thank-you', 'HomeController@thanks')->name('thank-you');
Route::post('stripe/webhook', '\Laravel\Cashier\Http\Controllers\WebhookController@handleWebhook');

app/Models/Category.php
<?php

namespace App\Models;

use App\Models\Scopes\NullScope;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Category extends Model
{
    use Sluggable;

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'category_id', 'name', 'slug'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        'deleted_at'
    ];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(new NullScope);
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function products()
    {
        return $this->hasMany(Product::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function subCategories()
    {
        return $this->hasMany(Category::class, 'category_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function subCategoryOf()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use App\Http\Controllers\Controller;
use App\Http\Requests\Category\StoreRequest;
use App\Http\Requests\Category\UpdateRequest;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::with('subCategoryOf')->paginate(15);

        return view('category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::where('category_id', 0)->get();

        return view('category.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StoreRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $request)
    {
        $category = $request->persist();

        return redirect()->route('categories.show', $category);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        return view('category.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $categories = Category::where('category_id', 0)->get();

        return view('category.edit', compact('category', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateRequest  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, Category $category)
    {
        $request->persist();

        return redirect()->route('categories.show', $category);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->products()->update(['category_id' => 0]);
        $category->delete();

        return redirect()->route('categories.index');
    }
}

resources/views/category/create.blade.php
@extends('layouts.admin')

@section('breadcrumbs')
    {!! Laracrumbs::render() !!}
@endsection

@section('admin-content')
    <div class="col-md-6">
        <form action="{{ route('categories.store') }}" method="post">
            {{ csrf_field() }}

            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name">Category</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Category 1"
                       value="{{ old('name') }}">
                @if ($errors->has('name'))
                    <p class="help-block">
                        <strong>{{ $errors->first('name') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('category_id') ? ' has-error' : '' }}">
                <label for="category_id">Category of</label>
                <select class="form-control" id="category_id" name="category_id">
                    <option value="0" selected>None</option>
                    @foreach($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                </select>
                @if ($errors->has('category_id'))
                    <p class="help-block">
                        <strong>{{ $errors->first('category_id') }}</strong>
                    </p>
                @endif
            </div>

            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.admin')

@section('breadcrumbs')
    {!! Laracrumbs::render($category) !!}
@endsection

@section('admin-content')
    <div class="col-md-6">
        <form action="{{ route('categories.update', $category) }}" method="post">
            {{ method_field('PUT') }}
            {{ csrf_field() }}

            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name">Category</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Category 1"
                       value="{{ old('name', $category->name) }}">
                @if ($errors->has('name'))
                    <p class="help-block">
                        <strong>{{ $errors->first('name') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('category_id') ? ' has-error' : '' }}">
                <label for="category_id">Category of</label>
                <select class="form-control" id="category_id" name="category_id">
                    <option selected>None</option>
                    @foreach($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                </select>
                @if ($errors->has('category_id'))
                    <p class="help-block">
                        <strong>{{ $errors->first('category_id') }}</strong>
                    </p>
                @endif
            </div>

            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.admin')

@section('breadcrumbs')
    {!! Laracrumbs::render() !!}
@endsection

@section('admin-content')
    <div class="col-md-9">
        <p>
            <a href="{{ route('categories.create') }}" class="btn btn-default">Create category</a>
        </p>
        <table class="table table-striped">
            <tr>
                <th>
                    #
                </th>
                <th>
                    Name
                </th>
                <th>
                    Sub Category
                </th>
                <th>
                    Sub Category Of
                </th>
            </tr>
            @foreach($categories as $category)
                <tr>
                    <td>
                        {{ $category->id }}
                    </td>
                    <td>
                        <a href="{{ route('categories.show', $category) }}">
                            {{ $category->name }}
                        </a>
                    </td>
                    <td>
                        @if(is_null($category->subCategoryOf))
                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        @else
                            <span class="glyphicon glyphicon-ok"></span>
                        @endif
                    </td>
                    <td>
                        @if(! is_null($category->subCategoryOf))
                            <a href="{{ route('categories.show', $category->subCategoryOf) }}">
                                {{ $category->subCategoryOf->name }}
                            </a>
                        @endif
                    </td>
                </tr>
            @endforeach
        </table>
        {{ $categories->links() }}
    </div>
@endsection

resources/views/category/product.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    {!! Laracrumbs::render($category) !!}
@endsection

@section('content')
    <div class="col-md-3">
        <div class="list-group">
            @if ($subCategory)
                <a href="{{ route('categories.products', $category->subCategoryOf) }}"
                   class="list-group-item{{ $selectedCategory == $category->subCategoryOf->id ? ' active' : '' }}">
                    {{ $category->subCategoryOf->name }}
                </a>
                @foreach($category->subCategoryOf->subCategories as $item)
                    <a href="{{ route('categories.products', $item) }}"
                       class="list-group-item{{ $selectedCategory == $item->id ? ' active' : '' }}">
                        <span class="sub-category">{{ $item->name }}</span>
                    </a>
                @endforeach
            @else
                <a href="{{ route('categories.products', $category) }}"
                   class="list-group-item{{ $selectedCategory == $category->id ? ' active' : '' }}">
                    {{ $category->name }}
                </a>
                @foreach($category->subCategories as $item)
                    <a href="{{ route('categories.products', $item) }}"
                       class="list-group-item{{ $selectedCategory == $item->id ? ' active' : '' }}">
                        <span class="sub-category">{{ $item->name }}</span>
                    </a>
                @endforeach
            @endif
        </div>
    </div>
    <div class="col-md-9">
        <div class="row">
            @foreach($products as $product)
                @include('layouts.component.product', compact('product'))
            @endforeach
        </div>
        <div class="row">
            <div class="col-md-12">
                {{ $products->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/category/show.blade.php
@extends('layouts.admin')

@section('breadcrumbs')
    {!! Laracrumbs::render($category) !!}
@endsection

@section('admin-content')
    <div class="col-md-9">
        <p>
            {{ $category->name }}
        </p>
        <p>
            @if(is_null($category->subCategoryOf))
                Sub categories:
                @foreach($category->subCategories as $subCategory)
                    <a href="{{ route('categories.show', $subCategory) }}">
                        {{ $subCategory->name }}</a>{{ ! $loop->last ? ', '  : '' }}
                @endforeach
            @else
                Category of:
                <a href="{{ route('categories.show', $category->subCategoryOf) }}">
                    {{ $category->subCategoryOf->name }}
                </a>
            @endif
        </p>

        <a href="{{ route('categories.edit', $category) }}" class="btn btn-default">Edit</a>
        <a href="{{ route('categories.destroy', $category) }}" class="btn btn-warning">Delete</a>
    </div>
@endsection