routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/about', 'AboutController@index')->name('about.index');
Route::get('/admin/about', 'AboutController@edit')->name('about.edit');
Route::put('/admin/about', 'AboutController@update')->name('about.update');

Route::get('/me', 'User\UserController@show')->name('me');
Route::get('/me/orders', 'User\UserOrderController@index')->name('users.order');

Route::get('/admin', 'Admin\AdminController@index')->name('admin.index')->middleware('auth', 'admin');
Route::get('/admin', 'Admin\AdminController@index')->name('admin.index')->middleware('auth', 'admin');

Route::get('/cart', 'CartController@index')->name('cart.index');
Route::get('/cart/{item}/remove', 'CartController@destroy')->name('cart.destroy');
Route::put('/cart/{item}', 'CartController@update')->name('cart.update');

Route::get('/search', 'SearchController@index')->name('search.index');
Route::post('/search', 'SearchController@index')->name('search.index');

Route::get('categories/{category}/products', 'CategoryProductController@show')->name('categories.products');

Route::resource('products', 'ProductController');
Route::get('products/{product}/add', 'ProductShoppingController@show');
Route::post('products/{product}/add', 'ProductShoppingController@store')->name('products.add');

Route::resource('reviews', 'Product\ProductReviewController');
Route::resource('orders', 'Admin\OrderController');

Route::get('/activate/{token}', 'ActivationController@show')->name('active');

Route::resource('categories', 'Admin\CategoryController', [
    'middleware' => ['auth', 'admin']
]);

Route::post('/cart/pay', 'CheckoutController@store')->name('checkout');
Route::get('/thank-you', 'HomeController@thanks')->name('thank-you');
Route::post('stripe/webhook', '\Laravel\Cashier\Http\Controllers\WebhookController@handleWebhook');

app/Models/Extensions/Uploadable.php
<?php

namespace App\Models\Extensions;

trait Uploadable
{
    /**
     * Boot the trait.
     */
    public static function bootUploadable()
    {
        static::saved(function ($model) {
            $model->uploadFiles();
        });

        static::deleting(function ($model) {
            $model->deleteFiles();
        });
    }

    /**
     * Upload the uploaded file from the request to the
     * file system.
     */
    public function uploadFiles()
    {
        if (request()->allFiles() > 0) {
            image($this)->handle();
        }
    }

    /**
     * Delete all files from a model.
     */
    public function deleteFiles()
    {
        image($this)->deleteFiles();
    }

    /**
     * Get the path to the image.
     */
    public function getImagePathAttribute()
    {
        return image($this)->get();
    }
}

resources/views/layouts/component/added.blade.php
<div class="modal fade" id="product-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Added to your shopping cart</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-8">
                        <div class="product-info">
                            <div class="pull-left product-thumbnail">
                                <img src="http://placehold.it/150x150" alt="Product" class="product-image" width="150px" height="150px">
                            </div>
                            <div class="pull-left">
                                <a href="#" class="product-link">
                                    <span class="product-name"></span>
                                </a>
                                <div class="product-price"></div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div>
                            <p>
                                <a href="#" data-dismiss="modal">Continue shopping</a>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-4 cart-options">
                        <div class="cart">
                            <a href="{{ route('cart.index') }}">Shopping cart</a>
                        </div>
                        <div class="cart-content">
                            <span class="pull-left cart-items"></span>
                            <span class="pull-right cart-costs"></span>
                            <div class="clearfix"></div>
                        </div>
                        <div class="shipping">
                            <span class="pull-left">Shipping: </span>
                            <span class="pull-right text-success">Free</span>
                            <div class="clearfix"></div>
                        </div>
                        <a href="{{ route('cart.index') }}" class="btn btn-success btn-lg">
                            Finish order
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/component/order.blade.php
<table id="cart" class="table table-hover table-condensed">
    <thead>
    <tr>
        <th style="width:50%">Product</th>
        <th style="width:10%">Price</th>
        <th style="width:8%">Quantity</th>
        <th style="width:22%" class="text-center">Subtotal</th>
        <th style="width:10%"></th>
    </tr>
    </thead>
    <tbody>
    @foreach(cart()->items() as $item)
        <tr data-url="{{ route('cart.update', $item) }}">
            <td data-th="Product">
                <div class="row">
                    <div class="col-sm-2 hidden-xs">
                        <img src="{{ $item->product->image_path }}" alt="Product" class="img-responsive"/>
                    </div>
                    <div class="col-sm-10">
                        <h4 class="nomargin">{{ $item->product->name }}</h4>
                        <p>{{ $item->product->description }}</p>
                    </div>
                </div>
            </td>
            <td data-th="Price">{{ money($item->product->price) }}</td>
            <td data-th="Quantity">
                <input type="number" class="form-control text-center product-amount" value="{{ $item->amount }}" min="1">
            </td>
            <td data-th="Subtotal" class="text-center">{{ money($item->amount * $item->product->price) }}</td>
            <td class="actions" data-th="">
                <a href="{{ route('cart.index') }}" class="btn btn-info btn-sm"><i class="fa fa-refresh"></i></a>
                <a href="{{ route('cart.destroy', $item ) }}" class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></a>
            </td>
        </tr>
    @endforeach
    </tbody>
    <tfoot>
    <tr class="visible-xs">
        <td class="text-center"><strong>Total {{ money(cart()->totalCosts()) }}</strong></td>
    </tr>
    <tr>
        <td><a href="{{ route('home') }}" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
        <td colspan="2" class="hidden-xs"></td>
        <td class="hidden-xs text-center"><strong>{{ money(cart()->totalCosts()) }}</strong></td>
        <td>
            <form action="{{ route('checkout') }}" method="POST">
                <script
                        src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key="pk_test_f7XenJlBudaV7yLioEHjA6gI"
                        data-amount="{{ cart()->totalCostsInCents() }}"
                        data-name="DrankShop"
                        data-description="De Drank Shop"
                        data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
                        data-locale="auto"
                        data-label="Checkout"
                        data-currency="eur">
                </script>
            </form>
        </td>
    </tr>
    </tfoot>
</table>

resources/views/layouts/component/product.blade.php
<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="{{ $product->image_path }}" alt="" width="auto" height="150px">
        <div class="caption">
            <h4 class="pull-right">&euro; {{ $product->price }}</h4>
            <h4><a href="{{ route('products.show', $product->slug) }}">{{ $product->name }}</a>
            </h4>
            <p>{{ $product->description }}</p>
        </div>
        <div class="ratings pull-left">
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star"></span>
            <span class="glyphicon glyphicon-star-empty"></span>
            <p>{{ mt_rand(2, 20) }} reviews</p>
        </div>
        <div class="cart-options pull-right">
            <a href="{{ route('products.add', $product->slug) }}" class="btn btn-primary btn-lg add-to-cart"
               data-turbolinks="false">
                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
            </a>
        </div>
        <div class="clearfix"></div>
    </div>
</div>