routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/about', 'AboutController@index')->name('about.index');
Route::get('/admin/about', 'AboutController@edit')->name('about.edit');
Route::put('/admin/about', 'AboutController@update')->name('about.update');

Route::get('/me', 'User\UserController@show')->name('me');
Route::get('/me/orders', 'User\UserOrderController@index')->name('users.order');

Route::get('/admin', 'Admin\AdminController@index')->name('admin.index')->middleware('auth', 'admin');
Route::get('/admin', 'Admin\AdminController@index')->name('admin.index')->middleware('auth', 'admin');

Route::get('/cart', 'CartController@index')->name('cart.index');
Route::get('/cart/{item}/remove', 'CartController@destroy')->name('cart.destroy');
Route::put('/cart/{item}', 'CartController@update')->name('cart.update');

Route::get('/search', 'SearchController@index')->name('search.index');
Route::post('/search', 'SearchController@index')->name('search.index');

Route::get('categories/{category}/products', 'CategoryProductController@show')->name('categories.products');

Route::resource('products', 'ProductController');
Route::get('products/{product}/add', 'ProductShoppingController@show');
Route::post('products/{product}/add', 'ProductShoppingController@store')->name('products.add');

Route::resource('reviews', 'Product\ProductReviewController');
Route::resource('orders', 'Admin\OrderController');

Route::get('/activate/{token}', 'ActivationController@show')->name('active');

Route::resource('categories', 'Admin\CategoryController', [
    'middleware' => ['auth', 'admin']
]);

Route::post('/cart/pay', 'CheckoutController@store')->name('checkout');
Route::get('/thank-you', 'HomeController@thanks')->name('thank-you');
Route::post('stripe/webhook', '\Laravel\Cashier\Http\Controllers\WebhookController@handleWebhook');

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id', 'email', 'status'
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'total_price'
    ];

    /**
     * Get the total price attribute.
     *
     * @return int
     */
    public function getTotalPriceAttribute()
    {
        $price = 0;

        foreach ($this->products as $product) {
            $price += $product->price * $product->pivot->amount;
        }

        return $price;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function products()
    {
        return $this->belongsToMany(Product::class)->withPivot('amount');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Order\UpdateRequest;
use App\Models\Order;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
    /**
     * OrderController constructor.
     */
    public function __construct()
    {
        $this->middleware('admin', ['except' => 'show']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::latest()->paginate(15);

        return view('order.index', compact('orders'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        $this->authorize('show', $order);

        return view('order.show', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        return view('order.edit', compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Order\UpdateRequest  $request
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRequest $request, Order $order)
    {
        $request->persist();

        return redirect()->route('orders.show', $order);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        $order->delete();

        return redirect()->route('orders.index');
    }
}

resources/views/order/create.blade.php
@extends('layouts.admin')

@section('breadcrumbs')
    {!! Laracrumbs::render() !!}
@endsection

@section('admin-content')
    <div class="col-md-6">
        <form action="{{ route('products.store') }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name">Product Name</label>
                <input type="text" class="form-control" id="name" name="name"
                       value="{{ old('name') }}">

                @if ($errors->has('name'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('name') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('category_id') ? ' has-error' : '' }}">
                <label for="category_id">Category of</label>
                <select class="selectable-group form-control" id="category_id" name="category_id">
                    <option value="" disabled selected>Select a category</option>
                    @foreach($categories as $category)
                        <option value="{{ $category->id }}" {{ selected($category) }}
                        class="category">{{ $category->name }}</option>

                        @foreach($category->subCategories as $subCategory)
                            <option value="{{ $subCategory->id }}" {{ selected($category) }}
                                    class="item">{{ $subCategory->name }}</option>
                        @endforeach
                    @endforeach
                </select>

                @if ($errors->has('category_id'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('category_id') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                <label for="description">Description</label>
                <textarea class="form-control product-description" id="description"
                          name="description">{{ old('description') }}</textarea>

                @if ($errors->has('description'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('description') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('cover') ? ' has-error' : '' }}">
                <label for="cover">Product image cover</label>
                <input type="file" id="cover" name="cover">
                <p class="help-block">This image is used as cover.</p>

                @if ($errors->has('cover'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('cover') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
                <label for="price">Price (in euros)</label>
                <div class="input-group">
                    <div class="input-group-addon">&euro;</div>
                    <input type="number" class="form-control" id="price" name="price" min="0" step="any"
                           value="{{ old('price', 0) }}">
                </div>

                @if ($errors->has('price'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('price') }}</strong>
                    </p>
                @endif
            </div>

            <div class="form-group{{ $errors->has('stock') ? ' has-error' : '' }}">
                <label for="stock">Stock</label>
                <input type="number" class="form-control" id="stock" name="stock" min="0"
                       value="{{ old('stock', 0) }}">
                <p class="help-block">The amount of products currently in stock.</p>

                @if ($errors->has('stock'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('stock') }}</strong>
                    </p>
                @endif
            </div>

            <button type="submit" class="btn btn-primary">Create</button>
        </form>
    </div>
@endsection

resources/views/order/edit.blade.php
@extends('layouts.admin')

@section('breadcrumbs')
    {!! Laracrumbs::render($order) !!}
@endsection

@section('admin-content')
    <div class="col-md-6">
        <form action="{{ route('orders.update', $order) }}" method="post">
            {{ method_field('PUT') }}
            {{ csrf_field() }}

            <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
                <label for="status">Status</label>
                <select class="form-control" id="status" name="status">
                    @foreach(['placed', 'shipped', 'delivered', 'unknown'] as $status)
                        <option value="{{ $status }}"{{ $order->status == $status ? ' selected' : '' }}>{{ $status }}</option>
                    @endforeach
                </select>

                @if ($errors->has('status'))
                    <p class="help-block has-error">
                        <strong>{{ $errors->first('status') }}</strong>
                    </p>
                @endif
            </div>

            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
@endsection

resources/views/order/index.blade.php
@extends('layouts.admin')

@section('breadcrumbs')
    {!! Laracrumbs::render() !!}
@endsection

@section('admin-content')
    <div class="col-md-9">
        <table class="table table-striped">
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Placed By
                </th>
                <th>
                    Status
                </th>
                <th>
                    Total costs
                </th>
                <th>
                    Ordered on
                </th>
            </tr>
            @foreach($orders as $order)
                <tr>
                    <td>
                        <a href="{{ route('orders.show', $order) }}">
                            # {{ $order->id }}
                        </a>
                    </td>
                    <td>
                        @if ($order->user)
                            {{ $order->user->name }}
                        @else
                            {{ $order->email }}
                        @endif
                    </td>
                    <td>
                        {{ $order->status }}
                    </td>
                    <td>
                        {{ money($order->total_price) }}
                    </td>
                    <td>
                        {{ $order->created_at }}
                    </td>
                </tr>
            @endforeach
        </table>
        {{ $orders->links() }}
    </div>
@endsection

resources/views/order/show.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    {!! Laracrumbs::render($order) !!}
@endsection

@section('content')
    <div class="col-md-3">
    </div>
    <div class="col-md-9">
        <p>
            ID: #{{ $order->id }}
        </p>
        <p>
            Ordered by:
            @if ($order->user)
                {{ $order->user->name }}
            @else
                {{ $order->email }}
            @endif
        </p>
        <p>
            Order status: {{ $order->status }}
        </p>
        <p>
            Total price: &euro; {{ $order->total_price }}
        </p>
        <p>
            Order placed on: {{ $order->created_at }}
        </p>
        <table class="table table-striped">
            <tr>
                <th>
                    Product
                </th>
                <th>
                    Amount
                </th>
                <th>
                    Price
                </th>
                <th>
                    Total Price
                </th>
            </tr>
            @foreach($order->products as $product)
                <tr>
                    <td>
                        <a href="{{ route('products.show', $product) }}">
                            {{ $product->name }}
                        </a>
                    </td>
                    <td>
                        {{ $product->pivot->amount }}
                    </td>
                    <td>
                        {{ money($product->price) }}
                    </td>
                    <td>
                        {{ money($product->price * $product->pivot->amount) }}
                    </td>
                </tr>
            @endforeach
        </table>
        @if (currentUser()->isAdmin())
            <a href="{{ route('orders.edit', $order) }}" class="btn btn-primary">Edit Order</a>
        @endif
    </div>
@endsection